[build]
  publish = "public"
  command = "npm install --legacy-peer-deps && npx gatsby build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200